"""add eligibilities table

Revision ID: d14cf26b8008
Revises: 22b9efe4c989
Create Date: 2026-09-22 12:54:23.330589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd14cf26b8008'
down_revision: Union[str, Sequence[str], None] = '22b9efe4c989'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eligibilities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('opportunity_id', sa.Uuid(), nullable=False),
    sa.Column('offers_visa_sponsorship', sa.Boolean(), nullable=True),
    sa.Column('german_language_required', sa.Boolean(), nullable=True),
    sa.Column('experience_level', sa.String(length=20), nullable=False),
    sa.Column('remote_friendly', sa.Boolean(), nullable=True),
    sa.Column('extracted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('opportunity_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eligibilities')
    # ### end Alembic commands ###
